# board target novo (ZMK Zephyr 4.1): seeeduino_xiao_ble -> xiao_ble//zmk
# https://zmk.dev/blog/2025/12/09/zephyr-4-1
---
include:
  - board: xiao_ble//zmk
    shield: chipper_left rgbled_adapter
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: xiao_ble//zmk
    shield: chipper_right rgbled_adapter
  - board: xiao_ble//zmk
    shield: settings_reset
